version: "3.9"

services:
  ors:
    image: openrouteservice/openrouteservice:latest
    container_name: ors
    ports:
      - "8080:8080"
    volumes:
      - ./ors:/home/ors
    restart: unless-stopped
    environment:
      REBUILD_GRAPHS: False
      XMS: 1g  # start RAM assigned to java
      XMX: 2g  # max RAM assigned to java. Rule of Thumb: <PBF-size> * <profiles> * 2
      # Example: 1.5 GB pbf size, two profiles (car and foot-walking)
      # -> 1.5 * 2 * 2 = 6. Set xmx to be AT LEAST `-Xmx6g`

  dlrg_haltern_vermissten_radius_karte:
    image: ghcr.io/marvinkinberger/dlrg_haltern_vermissten_radius_karte:latest
    container_name: dlrg_haltern_vermissten_radius_karte
    ports:
      - "80:80"
    restart: unless-stopped
