version: "3.9"

services:
  openrouteservice:
    image: openrouteservice/openrouteservice:latest
    container_name: openrouteservice
    ports:
      - "8081:8080"
    environment:
      - ORS_CONFIG=/ors/config/ors-config.yml
    volumes:
      - ./ors-config:/ors/config
      - ./ors-data:/ors/data
      - ./ors-graphs:/ors/graphs
    restart: unless-stopped

  dlrg_haltern_vermissten_radius_karte:
    image: ghcr.io/marvinkinberger/dlrg_haltern_vermissten_radius_karte:latest
    container_name: dlrg_haltern_vermissten_radius_karte
    ports:
      - "8080:80"
    restart: unless-stopped
